export const ALL_MEDIAS = 'ALL_MEDIAS'
export const ALL_MEDIAS_SUCCESS = 'ALL_MEDIAS_SUCCESS'
export const ALL_MEDIAS_FAILURE = 'ALL_MEDIAS_FAILURE'

export const REMOVE_MEDIA = 'REMOVE_MEDIA'
export const REMOVE_MEDIA_SUCCESS = 'REMOVE_MEDIA_SUCCESS'
export const REMOVE_MEDIA_FAILURE = 'REMOVE_MEDIA_FAILURE'

export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE'
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE'